package com.simon.rememberwords;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.simon.rememberwords.bean.Words;

import com.simon.rememberwords.WordsDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig wordsDaoConfig;

    private final WordsDao wordsDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        wordsDaoConfig = daoConfigMap.get(WordsDao.class).clone();
        wordsDaoConfig.initIdentityScope(type);

        wordsDao = new WordsDao(wordsDaoConfig, this);

        registerDao(Words.class, wordsDao);
    }
    
    public void clear() {
        wordsDaoConfig.clearIdentityScope();
    }

    public WordsDao getWordsDao() {
        return wordsDao;
    }

}
