package com.simon.rememberwords.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.simon.rememberwords.bean.Book;
import com.simon.rememberwords.bean.Word;

import com.simon.rememberwords.db.BookDao;
import com.simon.rememberwords.db.WordDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig bookDaoConfig;
    private final DaoConfig wordDaoConfig;

    private final BookDao bookDao;
    private final WordDao wordDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        bookDaoConfig = daoConfigMap.get(BookDao.class).clone();
        bookDaoConfig.initIdentityScope(type);

        wordDaoConfig = daoConfigMap.get(WordDao.class).clone();
        wordDaoConfig.initIdentityScope(type);

        bookDao = new BookDao(bookDaoConfig, this);
        wordDao = new WordDao(wordDaoConfig, this);

        registerDao(Book.class, bookDao);
        registerDao(Word.class, wordDao);
    }
    
    public void clear() {
        bookDaoConfig.clearIdentityScope();
        wordDaoConfig.clearIdentityScope();
    }

    public BookDao getBookDao() {
        return bookDao;
    }

    public WordDao getWordDao() {
        return wordDao;
    }

}
